
@baseUrl = http://localhost:3000/images/icon.png1665697124184.png

# Sends back all users
GET {{baseUrl}}/

###

# Signs up a new user
POST {{baseUrl}}/
content-type: application/json

{

    "userIds": "52",
   
}

